### ISSUE TITLE
training

### ISSUE THREAD

**Issue by 18219716332** [easton-cau/SOTR#18]
`Traceback (most recent call last):
  File "tools/train_net.py", line 218, in <module>
    launch(
  File "/root/miniconda3/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "tools/train_net.py", line 206, in main
    trainer = Trainer(cfg)
  File "tools/train_net.py", line 52, in __init__
    super(DefaultTrainer, self).__init__(model, data_loader, optimizer)
TypeError: __init__() takes 1 positional argument but 4 were given`

Excuse me, what is this problem?

**Comment by IamRecalcitrance** [comment]
Hello, I also encountered this problem, do you have a solution?

**Comment by IamRecalcitrance** [comment]
> `Traceback (most recent call last): File "tools/train_net.py", line 218, in <module> launch( File "/root/miniconda3/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch main_func(*args) File "tools/train_net.py", line 206, in main trainer = Trainer(cfg) File "tools/train_net.py", line 52, in __init__ super(DefaultTrainer, self).__init__(model, data_loader, optimizer) TypeError: __init__() takes 1 positional argument but 4 were given`
> 
> Excuse me, what is this problem?

Hello, I also encountered this problem, do you have a solution?

**Comment by Atharvat** [comment]
Same problem
Did anyone find a solution?

**Comment by azlanqazi2012** [comment]
You need to install detectron2 version v0.2.1 or former to solve this issue
